services:
  app:
    build: .
    container_name: app_main
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    networks:
      - my_network

  socket_server:
    build: .
    container_name: app_sock_server
    command: python main.py --socket
    ports:
      - "5001:5001"
    restart: always
    depends_on:
      - mongo
    networks:
      - my_network

  mongo:
    image: arm64v8/mongo:latest
    container_name: app_mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: viacheslav
      MONGO_INITDB_ROOT_PASSWORD: gHBf993$^^5
      MONGO_INITDB_DATABASE: message_db
    volumes:
      - ./mongo_storage:/data/db
    networks:
      - my_network

networks:
  my_network: